# Generated by Django 3.2.8 on 2021-10-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='authors',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='isbn',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='longDescription',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='pageCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='books',
            name='thumnail',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
