# Generated by Django 3.2.8 on 2021-10-13 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_remove_review_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user_id',
        ),
    ]
