# Generated by Django 3.2.8 on 2021-10-13 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_review_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
