# Generated by Django 3.2.8 on 2021-10-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_auto_20211015_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(null=True, upload_to='preview'),
        ),
    ]
